paths:
  package_path: "/home/intern/fyp_ws/src/HKU-2425FYP-RobotHelper/grasp/anygrasp/"
  record_path: "assets/anygrasp_records/"

parameters:
  max_gripper_width: 0.08
  gripper_height: 0.03
  max_grasp_number: 5
  top_down_grasp: True
  debug: True
  save_record: True